### ISSUE TITLE
Problem parsing string in file with latin-1 encoding

### ISSUE THREAD

**Issue by ethanhs** [we-like-parsers/pegen#209] opened 2020-02-18 10:49 UTC
Minimal example:

```
# -*- coding: latin_1 -*-
french = "tu pense qu'on peut m'utiliser comme ça?"
```

The string constant is `"tu pense qu'on peut m'utiliser comme Ã§a?"` with pegen.

**Comment by lysnikolaou** [comment] 2020-02-18 13:25
@pablogsal @gvanrossum Wouldn't this be solved by itself, once we integrate pegen into CPython?

**Comment by pablogsal** [comment] 2020-02-18 13:31
> Wouldn't this be solved by itself, once we integrate pegen into CPython?

Sort of, I think the problem is that this function call:

https://github.com/gvanrossum/pegen/blob/master/pegen/pegen.c#L607

is not taking the encoding at the moment. We can start hooking a call to `PyTokenizer_FindEncodingFilename` there but that will likely change when integrating this into CPython so we could wait until then.

**Comment by gvanrossum** [comment] 2020-05-07 23:51
I'm sure this is fixed in the CPython version, and the version here is too outdated to care.

**Closed by gvanrossum** 2020-05-07 23:51 UTC
